# site setting
title: one
baseurl: http://one.hatkit.com
site-name: HATKIT
favicon: favicon.png
logo:
banner: banner1.jpg  
markdown: kramdown
exclude: ['README.md']
permalink: pretty #to remove .html
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

#Gems
gems: [jekyll-paginate]
paginate: 60
paginate_path: "/blog/page:num/"
  
include: ['_pages']

